Common stats csv
ucsb-cs156-m23/proj-happycows-m23-10am-3 pull request #37
Opened 2023-08-19 23:20 UTC by mier2

## Overview
For this pr, I added csv functionality for common stats to implement #12
I also add back the decorator I forgot to add at `AverageCowHealthService.java`

## Screenshot
<img width="1454" alt="Screenshot 2023-08-19 at 4 16 42 PM" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/assets/84555609/e920a523-fdcc-4675-b90a-980f38bd686c">

## Tests
- [x] `mvn test`
- [x] `mvn test jacoco:report`
- [x] `mvn test org.pitest:pitest-maven:mutationCoverage`

Closes #36

2023-08-21 21:18 UTC, clin947 approved these changes
lgtm

2023-08-22 01:03 UTC, pconrad requested changes
LGTM for the most part... nice work.

Just one small change to request.

2023-08-22 01:03 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/helpers/CommonStatsCSVHelper.java
> +   */
Sorry about this, but I goofed when I wrote the comment you copied this from; I should have said pitest.  Let's change this to the following so that it will be easier for future devs to see what's going on.
```suggestion
  /**
   * This method is a hack to avoid a pitest issue; it isn't possible to 
   * exclude an individual method call from pitest coverage, but we can
   * exclude the entire method by name in the pitest settings in pom.xml
   * @param out stream to close
   * @param csvPrinter printer to close
   */
```

2023-08-22 01:28 UTC, pconrad approved these changes
LGTM

2023-08-22 01:28 UTC, merged