Common stats front end
ucsb-cs156-m23/proj-happycows-m23-10am-3 pull request #39
Opened 2023-08-20 02:55 UTC by mier2

## Overview
In this pr I implemented the front end of common stats.

## Screenshot
<img width="1322" alt="Screenshot 2023-08-19 at 7 51 37 PM" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/assets/84555609/9ff25190-b021-473d-860d-8557c0db7d06">

## Tests

- [ ] `npm test`
- [ ] `npm run coverage`
- [ ] `npx stryker run`

Closes #12

2023-08-21 21:31 UTC, clin947 approved these changes
lgtm

2023-08-22 18:31 UTC, pconrad requested changes
One small thing that should be fixed, then this is good to go.

2023-08-22 18:31 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/helpers/CommonStatsCSVHelper.java
> +  /*
No... this should be left the way it was.  This is a Javadoc comment, and the special `/** ` is needed to signal that.

See: https://www.baeldung.com/javadoc#javadoc-comments

See: 
```suggestion
  /**
```

2023-08-23 22:47 UTC, pconrad approved these changes

2023-08-23 22:47 UTC, pconrad approved these changes
LGTM!

2023-08-23 22:47 UTC, merged