[Andrew] Default Values + Tests
ucsb-cs156-m23/proj-happycows-m23-10am-3 pull request #43
Opened 2023-08-22 22:26 UTC by hanabicel

## Overview
In this pull request, I implemented default values for CommonsForm and AdminCreateCommonsPage. This also includes the addition of the "Ending Date" field which was absent in previous merges and extensive additions to the test suites. A re-formatting of the CreateCommons page was necessary to accommodate the "Ending Date" field, but still aligns with the guidelines in issue #1.

<img width="1402" alt="Screenshot 2023-08-22 at 3 18 15 PM" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-3/assets/46334533/60c3e739-b803-496d-9bd8-8c74c0d410f1">

## Tests

- [x] `npm test`
- [x] `npm run coverage`
- [x] `npm stryker npx stryker run -m src/main/components/Commons/CommonsForm.js`
- [x] `npm stryker npx stryker run -m src/main/pages/AdminCreateCommonsPage.js` 

Closes #41 and #42, which are subsets of #1.
Also completes 2/3 optional tasks in #1.
This PR closes #1 completely.

2023-08-23 16:36 UTC, mier2 requested changes, later dismissed

2023-08-23 16:36 UTC, mier2 commented on frontend/src/fixtures/commonsFixtures.js
> -            "startingDate": "2022-03-05T15:50:10",
The data type here for startingDate is different from fixtures. Maybe you should ensure that data type is consistent across entity and fixture

2023-08-23 16:36 UTC, mier2 commented on frontend/src/tests/pages/AdminCreateCommonsPage.test.js
> -            startingDate: '2022-03-05T00:00:00.000Z', // [1]
I am not sure if this is the line why you can't pass your test with the original fixture. But if this is the one, you are using ZonedDateTime not LocalDateTime when you assigning value to startingDate

2023-08-23 22:35 UTC, hanabicel commented on frontend/src/fixtures/commonsFixtures.js
> -            "startingDate": "2022-03-05T15:50:10",
Reverted this change because commonsFixtures ended up being irrelevant to the feature. Thanks for the catch.

2023-08-23 22:43 UTC, hanabicel commented on frontend/src/tests/pages/AdminCreateCommonsPage.test.js
> -            startingDate: '2022-03-05T00:00:00.000Z', // [1]
This isn't linked to the fixture at all but the test needs to include the zoneddatetime format regardless to accommodate default dates being selected for the user. Without the default date feature I wouldn't need to fix the format.

2023-08-23 23:00 UTC, ryan-he-8 approved these changes
lgtm

2023-08-23 23:05 UTC, pconrad approved these changes
LGTM!

Do we need to wait to merge this until the value is present in the backend?

2023-08-23 23:08 UTC, pconrad requested changes
There's nothing wrong with this PR per se... but I think we need a couple of other things first before this can be merged:

* Add endingDate field to Commons entity
* Add logic for endingDate to POST and PUT in backend.
* Add  endingDate to fixtures for commons and commonsPlus objects

Without that, I wonder if merging this might cause problems.

2023-08-23 23:10 UTC, hanabicel commented
> Do we need to wait to merge this until the value is present in the backend?
It might not have been a good idea for me to add the ending date feature so late in the project when the backend isn't being worked on by anyone else. I'll remove that entirely because issue #1 can be closed completely without it.

2023-08-23 23:25 UTC, hanabicel commented
I've removed everything relating to endingDate across all files. The only feature this PR will implement is the ability to have default values in all the fields. Requesting reviews from 2 of my team members again.

2023-08-23 23:28 UTC, ryan-he-8 approved these changes
lgtm

2023-08-24 17:57 UTC, pconrad approved these changes

2023-08-24 17:58 UTC, pconrad approved these changes
LGTM

2023-08-24 17:58 UTC, merged